### ISSUE TITLE
hi, how to run it on windows? Any model needed? steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [swkidd/react-native-japanese-ocr#2]
hi, how to run it on windows? Any model needed?

**Comment by swkidd** [comment]
Are you having trouble using the library on windows? Are you installing into a react-native project using the steps described in the README.md?

**Comment by nissansz** [comment]
I cannot understand your readme.md

**Comment by swkidd** [comment]
Closed as non specific
